### ISSUE TITLE
can't send email, reconnect emailjs API

### ISSUE THREAD

**Issue by gllmp** [gllmp/donats#32]
error message:
```
Failed to load resource: the server responded with a status of 412 ()

Gmail_API: Invalid grant. Please reconnect your Gmail account
```

**Comment by blufod** [comment]
I would like to know how you resolved this issue.

**Comment by blufod** [comment]
I experienced the same problem earlier but it was due to me changing my gmail account password. So simple reconnected my account by discounting my email js account in settings and connecting back my gmail account. Upon which I was asked to sign back in and authenticate. That's it, my emailJs is working now. Hope that helps

**Comment by bedamatta05** [comment]
@blufod works, thanks

**Comment by imane-bentaleb** [comment]
> I would like to know how you resolved this issue.



> I experienced the same problem earlier but it was due to me changing my gmail account password. So simple reconnected my account by discounting my email js account in settings and connecting back my gmail account. Upon which I was asked to sign back in and authenticate. That's it, my emailJs is working now. Hope that helps

how did u do that by small steps please

**Comment by numofran6** [comment]
> > I would like to know how you resolved this issue.
> 
> > I experienced the same problem earlier but it was due to me changing my gmail account password. So simple reconnected my account by discounting my email js account in settings and connecting back my gmail account. Upon which I was asked to sign back in and authenticate. That's it, my emailJs is working now. Hope that helps
> 
> how did u do that by small steps please

Heyy, found this which worked for me from stackoverflow:



I had the same and submitted the question, their answer was: "To solve this problem, you need to go to EmailJS dashboard -> Services, click on the Gmail service in your list, and reconnect your account. Please click on the checkbox "Send email on your behalf" to allow us to send the emails through your Gmail account. The new Gmail access popup leaves all permissions disabled by default."

**Comment by MMartinez2820** [comment]
si resolvi asi mismo:

Tuve lo mismo y envié la pregunta, su respuesta fue: "Para resolver este problema, debe ir al panel de EmailJS -> Servicios, hacer clic en el servicio de Gmail en su lista y volver a conectar su cuenta. Haga clic en la casilla de verificación "Enviar correo electrónico en su nombre" para permitirnos enviar los correos electrónicos a través de su cuenta de Gmail. La nueva ventana emergente de acceso a Gmail deja todos los permisos deshabilitados de forma predeterminada".

**Comment by Ehab97** [comment]
I had this issues and here the sepats that i have took to solve it select the service i have used from the email services then i edit it and disconnect and connect it again and it's worked fine

**Comment by UsamaMo** [comment]
also Is it safe to let email js send emails on your behalf?

**Comment by FlagElitov** [comment]
<img width="1119" alt="Screenshot 2024-12-06 at 15 33 22" src="https://github.com/user-attachments/assets/2cb4fc5c-5923-4d17-8a0a-6e72ab0354c5">


Just disconnect and connect it again and it's worked fine

**Comment by inesDrebenstedt** [comment]
Having the same problem. 
Disconnecting and reconnecting Gmail account did nothing. 
Created new service and authenticated with Gmail did nothing. 
Removing EmailJS access rights and the re-adding it by reconnecting my Gmail account in EmailJS did nothing.
Will probably move to different service.

Update: after a while it started working again, but I don't know why.
